Hw06
Fen99/Fintech-admins pull request #2
Opened 2018-07-26 15:37 UTC by Fen99

Домашнее задание №6 - PostgreSQL

2018-07-28 18:44 UTC, Frodox commented
Что-то не так с PR. тут изменения для двух дз, и 5-е и 6-е

2018-07-28 18:45 UTC, Frodox commented
видимо ветка была создана не из мастера)

2018-07-28 18:57 UTC, Frodox requested changes
Плюс два последних комита от неизвестного пользователя. Стоит git-config настроить у user-15 :) или себе добавить в профиль почту.

*Очень* тяжело читать код. Тут вот классы совсем не нужны)
Также не соблюдается граница в 80 символов (и даже 100). diff тяжело смотреть) (на будущее, хороший тон).

Питон скрипт нужно улучшить, чтобы он сам делал, что указано в ДЗ, при вызове. сейчас это библиотека, получается. Т.е. скрипт просто вызываем, и всё.

2018-07-28 18:57 UTC, Frodox commented on hw06/README.md
> +> su postgres -c 'initdb -D /usr/local/pgsql/data'
а это для чего? ни разу не использовал :)

2018-07-28 18:57 UTC, Frodox commented on hw06/README.md
> +> В postgresql.conf:
лучше как код выделять. три обратные кавычки сверху и снизу

2018-07-28 18:57 UTC, Frodox commented on hw06/README.md
> +> mkdir postgresql.service.d
что-то мне кажется, что это лишнее. ни разу не centos не требовалось создавать свой конфиг, и другие ребята справились без этого. всё точно точно прям?

2018-07-28 18:57 UTC, Frodox commented on hw06/README.md
> +> CREATE USER sample_user WITH PASSWORD 'qwerty';
за отдельного пользователя плюс в карму

2018-07-28 18:57 UTC, Frodox commented on hw06/python/shop_database.py
> +				print("Exception during execution! Connection will be closed, you will have to reconnect!")
ошибки в stderr

2018-07-28 18:57 UTC, Frodox commented on hw06/python/shop_database.py
> +				self.cursor.execute("DELETE FROM order_items WHERE order_item_id = {0};".format(results[i][0]))
переписываем без SQL-инъекций, безопасным вариантом :) 
http://initd.org/psycopg/docs/usage.html#passing-parameters-to-sql-queries

2018-07-28 20:05 UTC, Fen99 commented on hw06/README.md
> +> mkdir postgresql.service.d
Я воспользовался мануалом (https://www.postgresql.org/docs/current/static/server-start.html):
> When using systemd, you can use the following service unit file (e.g., at /etc/systemd/system/postgresql.service):

Можно было бы просто добавить в строчку в /etc/rc.local, но решил с systemd разобраться

2018-07-28 20:09 UTC, Fen99 commented on hw06/README.md
> +> su postgres -c 'initdb -D /usr/local/pgsql/data'
При установке же не создается папка /data, в которой будут файлы PostgreSQL (https://www.postgresql.org/docs/current/static/creating-cluster.html)
> To initialize a database cluster, use the command initdb, which is installed with PostgreSQL

Но мы же создаем в /usr/local/ папки от рута, поэтому нужно дать права пользователю postgres.

2018-07-28 20:32 UTC, Frodox commented on hw06/README.md
> +> mkdir postgresql.service.d
`/etc/rc.local` вообще пользоваться запрещено в 7-ке. К сожалению, эта дока не может покрыть все дистрибутивы, и дельного совета там нет. Лучше взять от сюда https://www.digitalocean.com/community/tutorials/how-to-install-and-use-postgresql-on-centos-7

2018-07-28 20:34 UTC, Frodox commented on hw06/README.md
> +> su postgres -c 'initdb -D /usr/local/pgsql/data'
я вообще не очень понял зачем выполнять команду `postgres -c 'initdb -D /usr/local/pgsql/data'` и создавать от рута папки в `/usr/local`.
оно всё само работает и в rpm-пакете же описано) мэинтейнеры дистрибутивов обо всё позаботились

2018-07-28 21:23 UTC, Fen99 commented on hw06/README.md
> +> su postgres -c 'initdb -D /usr/local/pgsql/data'
Понял, не выполнил postgresql-setup. Буду читать как устанавливать пакеты перед установкой более внимательно)
Кстати, у меня сервис не создался автоматически. Странно (postgresql-setup работает уже с созданным сервисом).

2018-08-03 11:23 UTC, Frodox commented
Переделай все PR , чтобы это был запрос на влитие в ветку с предыдущим ДЗ.  тогда тут будут изменения только по этому ДЗ,а не за все.

2018-08-03 11:30 UTC, Frodox approved these changes

2018-08-03 11:30 UTC, Frodox commented on hw06/changes.conf
> +ExecStart=/usr/bin/pg_ctl start -D ${PGDATA} -s -w -t 300
что это за конфиг?

2018-08-03 11:30 UTC, Frodox commented on hw06/changes.conf
> +ExecStart=/usr/bin/pg_ctl start -D ${PGDATA} -s -w -t 300
откуда эта переменная возьмётся?

2018-08-03 16:27 UTC, merged