HW09, nginx
Fen99/Fintech-admins pull request #5
Opened 2018-08-16 21:42 UTC by Fen99

2018-08-19 13:01 UTC, Frodox requested changes

2018-08-19 13:01 UTC, Frodox commented on hw09/README.md
> +- Кроме того, возникает проблема: nginx не запускается через systemd: "PID file /tmp/nginx.pid not readable (yet?) after start", сейчас тоже гуглю, разбираюсь. Возможно, это связано с другой проблемо
Предлагаю переделать на rpm-пакете, и  это всё решится. плюс делов на 10 минут)
т.к. используешь systemd, но вместе с make && make install...

2018-08-19 13:01 UTC, Frodox commented on hw09/conf.d/test-1.conf
> +        	vhost_traffic_status_display_format html;
Формат prometheus только я писал) говорил можно 2 loсation сделать

2018-08-19 13:01 UTC, Frodox commented on hw09/nginx.conf
> +		listen 8017;
почему такой порт?

2018-08-19 13:01 UTC, Frodox commented on hw09/nginx.conf
> +		server_name localhost;
как снаружи получить эти метрики в таком случае?

2018-08-19 14:21 UTC, Fen99 commented on hw09/conf.d/test-1.conf
> +        	vhost_traffic_status_display_format html;
У вас в задании была табличка, поэтому выбрал html. Prometheus - в /status/format/prometheus (конфигурация vts по умолчанию)

2018-08-19 14:22 UTC, Fen99 commented on hw09/nginx.conf
> +		listen 8017;
Это имитирует exporter, поэтому берем просто незанятый порт. У uwsgi был 1717, здесь взял 8017 по аналогии

2018-08-19 14:23 UTC, Fen99 commented on hw09/nginx.conf
> +		server_name localhost;
Обращение к my_host:8017/metrics прокируется nginx-ом на http://test-1/status/format/prometheus, что имитирует поведение exporter-а

2018-08-24 13:50 UTC, Frodox approved these changes

2018-08-25 17:56 UTC, merged